on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: package-lock=${{ hashFiles('package-lock.json') }}
          restore-keys: package-lock=
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
